name: First workflow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Helloo baby"
            echo "Ela Unav Kukka"
      - name: Print Bye
        run: echo "Dobbey"
